all: project3

project3: *.c
	gcc myfs_format.c -o myfs_format
	gcc myfs_inspect.c -o myfs_format
	gcc myfs_lib.c -o myfs_lib
	gcc myfs_lib_support.c -o myfs_lib_support
	gcc myfs_list.c -o myfs_list
	gcc myfs_mkd.c -o myfs_mkd
	gcc myfs_rmd.c -o myfs_rmd
	gcc myfs_stats.c -o myfs_stats
	gcc myfs_vdisk.c -o myfs_vdisk
clean:
	rm myfs*
